server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: razor-logs
    # entry_parser: raw
    static_configs:
    - targets:
        - localhost
      labels:
        job: razor
        user: "1"
        __path__: "/var/log/razor/*"

